title = 'My technology blog'
baseURL = 'https://hhgarland.me'
languageCode = 'en-us'
theme = 'hugo-blog-awesome'

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="uses"
    name = 'Uses'
    url = '/uses/'

[params]
  sitename = "My technology blog"
  defaultColor = "auto" # set color mode: dark, light, auto
  description = "My personal knowledgebase for telecommunications, Unified Communications, VoIP, networking, etc.."
  mainSections = ['posts']
  toc = false # set to false to disable table of contents 'globally'
  goToTop = true # set to false to disable 'go to top' button
  # additionalScripts = ['js/custom.js', 'js/custom-2.js']
  # Will try to load 'assets/js/custom.js' and 'assets/js/custom-2.js'.
  # Your custom scripts will be concatinated to one file `custom.js`.
  # When building for production it will be minified.
  # The file `custom.js` is loaded on each page (before body tag ends).

[params.author]
  # avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "My technology blog"
  name = "Hayden G"
  description = "My personal knowledgebase for telecommunications/UC/VoIP, networking, etc.."

# Allow to override webmanifest options
[params.webmanifest]
  name = "sitename" # will use "params.sitename" or "title" by default
  short_name = "sitename" # same as name
  start_url = "/" # will use homepage url by default
  theme_color = "#434648" # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
  background_color = "#fff" # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
  display = "standalone"

# Allow to override `browserconfig.xml` params (configuration for windows embeded browsers)
[params.browserconfig]
  TileColor = "#2d89ef" # default windows 10 blue tile color
  
[[params.socialIcons]]
name = "gitlab"
url = "https://gitlab.com/hhgarland"

[[params.socialIcons]]
name = "github"
url = "https://github.com/hhgarland"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/hhgarland/"

[tableOfContents]
startLevel = 2 # ToC starts from H2
endLevel = 4 # ToC ends at H4
ordered = false # generates <ul> instead of <ol>

